# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174abc455d32a09892565c95483a29a7e2252bbcf70f321e63bcac177304c8ba2c7b08cbd9f4a4b23c848f880dcd0ef78c102672903bae5ebc8d46c0bdb5282b

test:
  secret_key_base: 6954cb2754d3ee340ac885e9924ab63571a724b79bbedf42dae3d37b4fd91129045a49e545556c1a1be49d1784107106ba0d059447772adc42be3a4624ebd901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
